site_name: Qianyue's Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/QianyueW
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/QianyueWei
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/qianyue-wei-065120193/

nav:
  - Homepage: index.md
  - 游戏引擎技术:
      - 引擎基础架构: engine/page1.md
      - 游戏世界构成: engine/page2.md
      - Render: engine/page3.md
  - 算法与数据结构:
      - 编程题目总览: algorithm/main.md
      - 链表: algorithm/linkedlist.md
  - 待整理信息: other.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox
  
copyright: |
  &copy; 2023 <a href="https://github.com/QianyueW"  target="_blank" rel="noopener">Qianyue Wei</a>